name: Build Dockerfile on arm64

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --tag prover . --build-arg CMAKE_ARGS=-DNO_AVX=1
